services:
  app:
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh
    command: ['node', 'index.js']
    build:
      context: node
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: nginx
    networks:
      - node-network
    ports:
      - 8080:80

  db:
    build:
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
